Feature: Feature comparison status
    The comparison_status should reflect how two transcripts compare

    Scenario Outline: Evaluate comparison status
        Given a feature comparison <primary_contig_transcript>, <primary_contig_transcript_is_mane_select>, <primary_contig_transcript_partial>, <primary_contig_n_exons>, <primary_contig_n_introns>, <fix_contig_transcript>, <fix_contig_transcript_is_mane_select>, <fix_contig_transcript_partial>, <fix_contig_n_exons>, <fix_contig_n_introns>, <n_exons_equal>, <n_introns_equal>, <sequences_unequal_n_exons>, <sequences_unequal_n_introns>, <splice_sites_unequal_n>, <discordant_exon_numbering>
        Then the comparison status should be "<expected_status>"

        Examples:
            | primary_contig_transcript | primary_contig_transcript_is_mane_select | primary_contig_transcript_partial | primary_contig_n_exons | primary_contig_n_introns | fix_contig_transcript | fix_contig_transcript_is_mane_select | fix_contig_transcript_partial | fix_contig_n_exons | fix_contig_n_introns | n_exons_equal | n_introns_equal | sequences_unequal_n_exons | sequences_unequal_n_introns | splice_sites_unequal_n | discordant_exon_numbering | expected_status                                          |
            | NM_001012708.2            | True                                     | False                             | 1                      | 0                        | NM_001012708.2        | True                                 | False                         | 1                  | 0                    | True          | True            | 0                         | 0                           | 0                      | False                     | Identical                                                |
            | NM_001365790.2            | True                                     | False                             | 5                      | 4                        | NM_001365790.2        | True                                 | False                         | 5                  | 4                    | True          | True            | 0                         | 0                           | 0                      | False                     | Identical                                                |
            | XR_007068791.1            | False                                    | False                             | 1                      | 0                        | None                  | False                                | None                          | 0                  | 0                    | False         | True            | -1                        | 0                           | 0                      | None                      | Not comparable - Primary or Fix transcript not available |
            | XR_007062546.1            | False                                    | False                             | 3                      | 2                        | None                  | False                                | None                          | 0                  | 0                    | False         | False           | -1                        | -1                          | -1                     | None                      | Not comparable - Primary or Fix transcript not available |
            | NR_001553.2               | False                                    | False                             | 4                      | 3                        | NR_001553.2           | False                                | False                         | 4                  | 3                    | True          | True            | 0                         | 2                           | 0                      | False                     | Different - Exons or introns sequences differ            |
            | NM_021640.4               | True                                     | False                             | 7                      | 6                        | NM_021640.4           | True                                 | False                         | 7                  | 6                    | True          | True            | 2                         | 2                           | 0                      | False                     | Different - Exons or introns sequences differ            |
            | NM_001277303.1            | True                                     | False                             | 11                     | 10                       | NM_001277303.1        | True                                 | False                         | 12                 | 11                   | False         | False           | -1                        | -1                          | -1                     | None                      | Different - No. of exons and introns differ              |
            | NR_158192.1               | False                                    | False                             | 6                      | 5                        | NR_158192.1           | False                                | False                         | 7                  | 6                    | False         | False           | -1                        | -1                          | -1                     | None                      | Different - No. of exons and introns differ              |
            | NM_024607.4               | True                                     | False                             | 2                      | 1                        | NM_024607.4           | True                                 | False                         | 2                  | 1                    | True          | True            | 2                         | 1                           | 2                      | True                      | Different - Discordant/flipped exon numbering            |
            | NM_001040032.2            | True                                     | False                             | 4                      | 3                        | NM_001040032.2        | True                                 | False                         | 4                  | 3                    | True          | True            | 4                         | 3                           | 6                      | True                      | Different - Discordant/flipped exon numbering            |
            | NM_022755.6               | True                                     | False                             | 13                     | 12                       | NM_022755.6           | True                                 | True                          | 8                  | 7                    | False         | False           | -1                        | -1                          | -1                     | None                      | Not comparable - Fix transcript is partial               |
            | NM_001367949.2            | True                                     | False                             | 28                     | 27                       | NM_001367949.2        | True                                 | True                          | 4                  | 3                    | False         | False           | -1                        | -1                          | -1                     | None                      | Not comparable - Fix transcript is partial               |
            | NR_036687.1               | False                                    | False                             | 3                      | 2                        | NR_036687.1           | False                                | False                         | 3                  | 2                    | True          | True            | 3                         | 2                           | 1                      | False                     | Different - Splice sites differ                          |
            | NM_001164449.1            | True                                     | False                             | 4                      | 3                        | NM_001164449.1        | True                                 | False                         | 4                  | 3                    | True          | True            | 3                         | 3                           | 1                      | False                     | Different - Splice sites differ                          |